<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version Condition="'$(Version)'==''">0.0.0</Version>
	</PropertyGroup>


	<ItemGroup Condition="Exists('$(YMM4_PATH)\YukkuriMovieMaker.Plugin.dll')">
		<Reference Include="YukkuriMovieMaker.Plugin"
				   HintPath="$(YMM4_PATH)\YukkuriMovieMaker.Plugin.dll"
				   Private="false" ExcludeAssets="runtime" />
		<Reference Include="YukkuriMovieMaker.Controls"
				   HintPath="$(YMM4_PATH)\YukkuriMovieMaker.Controls.dll"
				   Private="false" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup Condition="!Exists('$(YMM4_PATH)\YukkuriMovieMaker.Plugin.dll')">
		<Reference Include="YukkuriMovieMaker.Plugin"
				   HintPath="..\libs\YukkuriMovieMaker.Plugin.dll"
				   Private="false" ExcludeAssets="runtime" />
		<Reference Include="YukkuriMovieMaker.Controls"
				   HintPath="..\libs\YukkuriMovieMaker.Controls.dll"
				   Private="false" ExcludeAssets="runtime" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\YmmpxLib\YMMPXLib\YMMPXLib.csproj" />
	</ItemGroup>

	<Target Name="CopyToYMM4" AfterTargets="Build"
			Condition="Exists('$(YMM4_PATH)')">

		<PropertyGroup>
			<PluginOutputDir>
				$(YMM4_PATH)\user\plugin\$(AssemblyName)
			</PluginOutputDir>
		</PropertyGroup>

		<MakeDir Directories="$(PluginOutputDir)"
				 Condition="!Exists('$(PluginOutputDir)')" />

		<ItemGroup>
			<PluginFiles Include="$(TargetDir)$(AssemblyName).dll" />
			<PluginFiles Include="$(TargetDir)YMMResourcePackager.YmmpxLib.dll"
						 Condition="Exists('$(TargetDir)YMMResourcePackager.YmmpxLib.dll')" />
			<PluginFiles Include="$(TargetDir)$(AssemblyName).deps.json"
						 Condition="Exists('$(TargetDir)$(AssemblyName).deps.json')" />
		</ItemGroup>

		<Copy SourceFiles="@(PluginFiles)"
			  DestinationFolder="$(PluginOutputDir)" />
	</Target>



</Project>
