<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version Condition="'$(Version)'==''">0.0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\YMMResourcePackager.Shared\YMMResourcePackager.Shared.csproj" />
  </ItemGroup>
</Project>
